### ISSUE TITLE
Could not find a suitable interface

### ISSUE THREAD

**Issue by sergiolepore** [linux-thinkpad/hdapsd#13]
Hello, I'm getting this message every time I start the daemon:

```
Could not find a suitable interface
```

What's wrong? I'm using Ubuntu 14.04 on a HP Envy 17 Laptop (with HP 3D DriveGuard support).

**Comment by louy2** [comment]
Meeting this on a ThinkPad T430. It is not supported by `tp-smapi` according to various sources. Is this one just not supported now?

**Comment by evgeni** [comment]
@louy2 yeah, newer thinkpads are not supported as there is no driver for the sensor.
